### ISSUE TITLE
Database: support string values

### ISSUE THREAD

**Issue by bcebere** [OpenMined/PIR#21]
## Description
In order to complete the PSI integration, we need to support string values in the database class.

We need to encode the strings in seal::Plaintext objects.

**Comment by kshehata** [comment]
I think I've figured out how we can do this. We basically need to write an encoder that spreads the string over the coefficients of the plaintext polynomial. Each coefficient is bounded by the plaintext modulus. Because we don't do any operations other than multiplying by 1 (mod t) and summing values that should be either a value or 0, we don't have to worry about overflow. If the plaintext modulus is t, then we can store up to floor(log2(t)) in each coefficient.

Basically, all we have to do is loop over the string, pack as many bits as we can into the current coefficient until we run out of space in the coefficient, then move on to the next coefficient. Do that until we've gone through the entire string.

A few notes on this:
* As described above, this only works because we're only ever multiplying by 1 (mod t) or summing with zero, so we won't have problems with wraparound.
* It's possible that we could calculate the number base t and use that, which would be slightly more efficient, but seems more complicated for a small gain.
* The number of values that can be stored in a plaintext are: (poly_modulus_degree / ceil(bits_per_db_item / floor_log_t))

**Comment by bcebere** [comment]
One other idea that I was thinking about was:
 - Encode the string to hex representation.
 - Load the hex representation in a seal::BigUInt object.
 - Adapt the current uint64 usage to BigUInt(maybe a template)  - it should support the same operations, I hope.

**Comment by kshehata** [comment]
The current way to encode a uint64 is to use one bit per coefficient. For the general case that works because you don't know what operations will be done and that leaves lots of room to avoid overflow. In our case that'll be very inefficient.

**Comment by kshehata** [comment]
Also: by string I'm assuming a byte array, which would be a text string, but that would be very inefficient as well.

**Comment by kshehata** [comment]
I see what you're getting at with BigUInt encoder. While that would work, it's suboptimal. Looks at [IntegerEncoder::encode](https://github.com/microsoft/SEAL/blob/master/native/src/seal/intencoder.cpp#L118). What happens there is that each bit of the BigUInt is encoded as a single plaintext coefficient. While that may be a good idea for other use cases to avoid overflow, in our case it leaves a lot of unused bits.

**Comment by kshehata** [comment]
Your suggestion to use BigUInt is a good one though. I've added an [optimal packing encoder on a branch here](https://github.com/OpenMined/PIR/tree/pack_values) using that as a basis. Since this is done at DB setup I'm not worried about how long it'll take, and actually the more bits the better. Still need to test it with the actual PIR
